### ISSUE TITLE
Small issues with writing to variable attrs

### ISSUE THREAD

**Issue by dvalters** [dvalters/fuse-netcdf#22]
Writing to variable attributes is working in principle now, just needs a bit of tidying up (more details in the emails):

Creating a new variable:

Step 1: in Directory `blh` (boundary layer height)
```
touch misc_meta
ll
dvalters@helmsdale blh]$ ll
total 0
-rw-r--r--. 1 dvalters dvalters      18 Aug  7 13:58 add_offset
-rw-r--r--. 1 dvalters dvalters 8147569 Aug  7 13:58 DATA_REPR
-rw-r--r--. 1 dvalters dvalters       7 Aug  7 13:58 _FillValue
-rw-r--r--. 1 dvalters dvalters      22 Aug  7 13:58 long_name
-rw-r--r--. 1 dvalters dvalters       7 Aug  7 13:58 misc_meta
-rw-r--r--. 1 dvalters dvalters       7 Aug  7 13:58 missing_value
-rw-r--r--. 1 dvalters dvalters      20 Aug  7 13:58 scale_factor
-rw-r--r--. 1 dvalters dvalters       2 Aug  7 13:58 units
```
Great!

Step 2: added some misc text e.g. "foobar" with vim.

`ncdump -h`
```
	short blh(time, latitude, longitude) ;
		blh:scale_factor = 0.108739383344517 ;
		blh:add_offset = 3570.14367055165 ;
		blh:_FillValue = -32767s ;
		blh:missing_value = -32767s ;
		blh:units = "m" ;
		blh:long_name = "Boundary layer height",
		blh:misc_meta = "foobar\n",
			"" ;
```
It adds a newline character `\n` and an empty string to the misc_meta attribute

Also happens when you add to an existing variable:

`ncdump -h`
```
	short blh(time, latitude, longitude) ;
		blh:scale_factor = 0.108739383344517 ;
		blh:add_offset = 3570.14367055165 ;
		blh:_FillValue = -32767s ;
		blh:missing_value = -32767s ;
		blh:units = "m" ;
		blh:long_name = "The Boundary layer height\n",    <-- another newline?
			"" ;     
		blh:misc_meta = "foobar\n",
			"" ;
```

To investigate further...

**Comment by blazk** [comment]
@dvalters indeed, well spotted! Vim adds a new line to the end of file when there is none, and it gets written to the attribute...

I did not notice this because I was editing attributes with "cat foobar > long_name" which does not add extra new line.

I think one solution would be to .rstrip('\n') the string when setting an attribute.

The attribute representation plugin adds a new line if there is no new line at the end - this is so that the attribute text looks neat when viewing in an editor or with "cat long_name".
